--creating employee table

CREATE TABLE employee (
    emp_id     NUMERIC(10) NOT NULL,
    emp_name   VARCHAR2(50) NOT NULL,
    salary     NUMBER(20),
    dept_name  VARCHAR2(50),
    CONSTRAINT emp_pk PRIMARY KEY ( emp_id )
);


--creating department table

CREATE TABLE department (
    dept_id    NUMERIC(10) NOT NULL,
    dept_name  VARCHAR2(50) NOT NULL,
    emp_id           NUMERIC(10) NOT NULL,
    CONSTRAINT fk_dept FOREIGN KEY ( emp_id )
        REFERENCES employee ( emp_id )
);


--creating log data table

CREATE TABLE log_data
(
AUDIT_ID	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
TABLE_NAME	VARCHAR2(30),
TRANSACTION_NAME	VARCHAR2(10),
TRANSACTION_DATE	VARCHAR2(20),
EMP_ID	NUMBER(10),
EMP_NAME VARCHAR2(20),
SALARY NUMBER(30),
DEPT_NAME	VARCHAR2(30),
DEPT_ID	NUMBER(20)
);
